server:
  port: 9001

spring:
  application:
    name: sc-service-provider
  datasource:
    name: test
    url:  jdbc:oracle:thin:@163.1.9.94:1521:ebank
    username: ebankUAT
    password: ebankUAT
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true

  redis:
    host: localhost
    port: 6379
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.entiry

# 分页配置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

eureka:
  instance:
    prefer-ip-address: true # 以ip注册
    lease-expiration-duration-in-seconds:  30 #心跳时间
  client:
    service-url:
       defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka

#服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
#默认90s
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
#服务刷新时间配置，每隔这个时间会主动心跳一次
#默认30s
eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
#eureka client刷新本地缓存时间
#默认30s
eureka:
  client:
    registryFetchIntervalSeconds: 15